//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 09:24:16 AM BST 
//


package XSDClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChannelHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChannelHeader"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ChannelCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TramissionRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LogNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelHeader", propOrder = {
    "recordType",
    "channelCode",
    "tramissionRegion",
    "logNumber",
    "date"
})
public class ChannelHeader {

    @XmlElement(name = "RecordType")
    protected int recordType;
    @XmlElement(name = "ChannelCode", required = true)
    protected String channelCode;
    @XmlElement(name = "TramissionRegion", required = true)
    protected String tramissionRegion;
    @XmlElement(name = "LogNumber")
    protected int logNumber;
    @XmlElement(name = "Date")
    protected int date;

    /**
     * Gets the value of the recordType property.
     * 
     */
    public int getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     */
    public void setRecordType(int value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the channelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * Sets the value of the channelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelCode(String value) {
        this.channelCode = value;
    }

    /**
     * Gets the value of the tramissionRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTramissionRegion() {
        return tramissionRegion;
    }

    /**
     * Sets the value of the tramissionRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTramissionRegion(String value) {
        this.tramissionRegion = value;
    }

    /**
     * Gets the value of the logNumber property.
     * 
     */
    public int getLogNumber() {
        return logNumber;
    }

    /**
     * Sets the value of the logNumber property.
     * 
     */
    public void setLogNumber(int value) {
        this.logNumber = value;
    }

    /**
     * Gets the value of the date property.
     * 
     */
    public int getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     */
    public void setDate(int value) {
        this.date = value;
    }

}
