//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 09:24:16 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.jrecordbind.org/jrb/CH_Header", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package XSDClasses;
