//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.30 at 10:35:42 AM BST 
//


package xsdvali.breaksony.breaksonyheader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChannelTrailer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChannelTrailer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DetailCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelTrailer", propOrder = {
    "recordType",
    "detailCount"
})
public class ChannelTrailer {

    @XmlElement(name = "RecordType")
    protected int recordType;
    @XmlElement(name = "DetailCount")
    protected int detailCount;

    /**
     * Gets the value of the recordType property.
     * 
     */
    public int getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     */
    public void setRecordType(int value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the detailCount property.
     * 
     */
    public int getDetailCount() {
        return detailCount;
    }

    /**
     * Sets the value of the detailCount property.
     * 
     */
    public void setDetailCount(int value) {
        this.detailCount = value;
    }

}
