//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.30 at 12:41:45 PM BST 
//


package xsdvali.breaksony.breaksonyheader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ChannelCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TramissionRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BreakLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BreakType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BreakPosition" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BreakID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataRecord", propOrder = {
    "recordType",
    "channelCode",
    "tramissionRegion",
    "date",
    "startTime",
    "breakLength",
    "breakType",
    "breakPosition",
    "breakID"
})
public class DataRecord {

    @XmlElement(name = "RecordType")
    protected int recordType;
    @XmlElement(name = "ChannelCode", required = true)
    protected String channelCode;
    @XmlElement(name = "TramissionRegion", required = true)
    protected String tramissionRegion;
    @XmlElement(name = "Date")
    protected int date;
    @XmlElement(name = "StartTime")
    protected int startTime;
    @XmlElement(name = "BreakLength")
    protected int breakLength;
    @XmlElement(name = "BreakType", required = true)
    protected String breakType;
    @XmlElement(name = "BreakPosition", required = true)
    protected String breakPosition;
    @XmlElement(name = "BreakID")
    protected int breakID;

    /**
     * Gets the value of the recordType property.
     * 
     */
    public int getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     */
    public void setRecordType(int value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the channelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * Sets the value of the channelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelCode(String value) {
        this.channelCode = value;
    }

    /**
     * Gets the value of the tramissionRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTramissionRegion() {
        return tramissionRegion;
    }

    /**
     * Sets the value of the tramissionRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTramissionRegion(String value) {
        this.tramissionRegion = value;
    }

    /**
     * Gets the value of the date property.
     * 
     */
    public int getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     */
    public void setDate(int value) {
        this.date = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     */
    public int getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     */
    public void setStartTime(int value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the breakLength property.
     * 
     */
    public int getBreakLength() {
        return breakLength;
    }

    /**
     * Sets the value of the breakLength property.
     * 
     */
    public void setBreakLength(int value) {
        this.breakLength = value;
    }

    /**
     * Gets the value of the breakType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakType() {
        return breakType;
    }

    /**
     * Sets the value of the breakType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakType(String value) {
        this.breakType = value;
    }

    /**
     * Gets the value of the breakPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakPosition() {
        return breakPosition;
    }

    /**
     * Sets the value of the breakPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakPosition(String value) {
        this.breakPosition = value;
    }

    /**
     * Gets the value of the breakID property.
     * 
     */
    public int getBreakID() {
        return breakID;
    }

    /**
     * Sets the value of the breakID property.
     * 
     */
    public void setBreakID(int value) {
        this.breakID = value;
    }

}
