//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.30 at 12:41:45 PM BST 
//


package xsdvali.breaksony.breaksonyheader;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xsdvali.breaksony.breaksonyheader package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Main_QNAME = new QName("http://XSDVali/BreakSony/BreakSonyHeader", "main");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xsdvali.breaksony.breaksonyheader
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataRecord }
     * 
     */
    public DataRecord createDataRecord() {
        return new DataRecord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataRecord }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataRecord }{@code >}
     */
    @XmlElementDecl(namespace = "http://XSDVali/BreakSony/BreakSonyHeader", name = "main")
    public JAXBElement<DataRecord> createMain(DataRecord value) {
        return new JAXBElement<DataRecord>(_Main_QNAME, DataRecord.class, null, value);
    }

}
